server:
  servlet:
    context-path:


spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    url: jdbc:mysql://localhost:3306/city?useUnicode=true&characterEncoding=utf-8
    url: jdbc:log4jdbc:mysql://localhost:3306/springdatamongodb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间

  data:
    mongodb:
      uri: "mongodb://localhost:27017/mongodb001"

mybatis-plus:
  configuration:
    # 关闭驼峰命名规则
    map-underscore-to-camel-case: false